#[allow(unused_imports)]
pub use crate::controller_system::FromInputEvent;
#[allow(unused_imports)]
pub use crate::globals;
#[allow(unused_imports)]
pub use crate::ssr::BrickError;
#[cfg(brick_dom)]
#[allow(unused_imports)]
pub use crate::state_mgmt::spawn_local;
#[allow(unused_imports)]
pub use crate::state_mgmt::{
    BrickAction, BrickLifecycle, BrickModel, Cascade, List, Load, Resource, Signal, cascade, spring,
};
#[allow(unused_imports)]
pub use crate::theme::{
    BRICK_DARK_THEME, BRICK_THEME, Color, Em, Pct, Px, Rem, SLATE_DARK_THEME, SLATE_THEME, Space,
    Style, Theme, ThemeSet,
};
#[allow(unused_imports)]
pub use crate::validation::Validate;
pub use brick_proc_macros::{
    compute, controller, css, global, keyframes, live, model, routes, server, store, style, view,
};
#[allow(unused_imports)]
pub use std::cell::RefCell;
#[allow(unused_imports)]
pub use std::rc::Rc;

#[macro_use]
pub mod view_helpers;
#[allow(unused_imports)]
pub use crate::routing::{LinkExt, Linkable, NavLink, Route, StrLinkExt};
pub(crate) use view_helpers::{BrickContainer, ReactiveDiv};
#[allow(unused_imports)]
pub use view_helpers::{BrickFragment, BrickRow, SvgViewMapped, ViewMapped};

mod composites;
pub use composites::*;

mod conditionals;
#[allow(unused_imports)]
pub use conditionals::*;

mod resolve;
#[allow(unused_imports)]
pub use resolve::ViewResolve;

#[macro_use]
mod load;

#[macro_use]
mod idle;

#[macro_use]
mod wait;

#[macro_use]
mod catch;

mod list;
pub use list::ViewList;

mod flip_list;
pub use flip_list::FlipList;

mod leafs;
pub use leafs::*;

mod form;
#[allow(unused_imports)]
pub use form::BrickForm;

pub mod svg;
#[allow(unused_imports)]
pub use svg::*;

mod keyframes;
#[allow(unused_imports)]
pub use crate::theme::{Deg, Ms, Rad, Turn};
#[allow(unused_imports)]
pub use keyframes::{
    CssAngle, CssLength, KeyframeName, Keyframes, Stop, Transform, keyframes, stop, transform,
};

mod animation;
#[allow(unused_imports)]
pub use animation::{AnimateExt, AnimationBuilder, Easing, FillMode, stagger};

pub trait Brick {
    fn render_into(&self, parent: &crate::renderer::BrickNode);
    fn attach_listeners(&self) {}
    fn detach(&self) {}
    fn is_fragment(&self) -> bool {
        false
    }
}

impl<T: Brick + ?Sized> Brick for Box<T> {
    fn render_into(&self, parent: &crate::renderer::BrickNode) {
        (**self).render_into(parent);
    }
    fn attach_listeners(&self) {
        (**self).attach_listeners();
    }
    fn detach(&self) {
        (**self).detach();
    }
    fn is_fragment(&self) -> bool {
        (**self).is_fragment()
    }
}

/// Render a component to an HTML string. Creates a temporary container, calls
/// `render_into`, and serialises the container's children. Used everywhere an
/// HTML string is needed (SSR, DOM `set_inner_html` bridges, tests).
pub fn render_to_html(brick: &dyn Brick) -> String {
    use crate::renderer::{BrickRenderer as _, HtmlRenderer};
    let parent = HtmlRenderer::element("div");
    brick.render_into(&parent);
    parent.inner_html_string()
}

/// Type-erase a `Brick` into a heap allocation.
pub trait IntoBrick {
    fn into_brick(self) -> Box<dyn Brick>;
}

impl<T: Brick + Sized + 'static> IntoBrick for Box<T> {
    fn into_brick(self) -> Box<dyn Brick> {
        self
    }
}

impl IntoBrick for Box<dyn Brick> {
    fn into_brick(self) -> Box<dyn Brick> {
        self
    }
}

/// Anything that can be placed as a child in `children!` or `row!`, or mounted
/// at the application root.
///
/// Implemented automatically for:
/// - `Box<T: Brick>` — all element builders and containers
/// - `Box<dyn Brick>` — already-erased components
/// - Concrete component model structs — `impl IntoComponent` generated by `#[view]`
pub trait IntoComponent {
    fn into_component(self) -> Box<dyn Brick>;

    /// Render and mount this component into a DOM element, wiring all event
    /// listeners. Event wiring is a no-op outside `brick_dom` builds.
    fn mount(self, slot: &web_sys::HtmlElement)
    where
        Self: Sized,
    {
        let component = self.into_component();
        slot.set_inner_html(&crate::view_components::render_to_html(&*component));
        component.attach_listeners();
    }
}

impl IntoComponent for Box<dyn Brick> {
    fn into_component(self) -> Box<dyn Brick> {
        self
    }
}

impl<T: Brick + Sized + 'static> IntoComponent for Box<T> {
    fn into_component(self) -> Box<dyn Brick> {
        self
    }
}
// Concrete component structs get `impl IntoComponent` generated by #[view].

// ── Slot ─────────────────────────────────────────────────────────────────────

/// An injectable UI content slot — an opaque, cheaply-cloneable handle to a
/// rendered sub-tree. Declare on a model field with `#[slot]` and create at
/// the call site with the `slot!` macro.
///
/// ```rust,ignore
/// Card { title: "Settings", children: slot!(row! { button("Save"), button("Cancel") }), ..cascade() }
/// ```
pub struct Slot(std::rc::Rc<dyn Brick>);

impl Slot {
    #[allow(dead_code)]
    pub fn from_component(c: Box<dyn Brick>) -> Self {
        Slot(std::rc::Rc::from(c))
    }
}

impl Clone for Slot {
    fn clone(&self) -> Self {
        Slot(std::rc::Rc::clone(&self.0))
    }
}

impl Default for Slot {
    fn default() -> Self {
        Slot(std::rc::Rc::new(EmptySlot))
    }
}

impl From<Box<dyn Brick>> for Slot {
    fn from(b: Box<dyn Brick>) -> Self {
        Slot(std::rc::Rc::from(b))
    }
}

impl Brick for Slot {
    fn render_into(&self, parent: &crate::renderer::BrickNode) {
        self.0.render_into(parent);
    }
    fn detach(&self) {
        self.0.detach();
    }
}

// Use &Slot so that field access through Deref (which yields &Slot, not owned Slot)
// works without requiring a move. Cloning an Rc is cheap. Owned Slot bindings
// auto-ref to &Slot transparently.
impl IntoComponent for &Slot {
    fn into_component(self) -> Box<dyn Brick> {
        Box::new(self.clone())
    }
}

struct EmptySlot;
impl Brick for EmptySlot {
    fn render_into(&self, parent: &crate::renderer::BrickNode) {
        use crate::renderer::{BrickRenderer as _, Renderer};
        Renderer::append(parent, &Renderer::text(""));
    }
}

/// Escape `&`, `<`, `>` so a plain string is safe to place inside an HTML element.
pub fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

// ── Scoped style injection ────────────────────────────────────────────────────

/// The `#[view]` macro stores the current component's instance class here so
/// that the `style!` declarative macro can read it without hygiene conflicts.
/// WASM is single-threaded so this is always safe; native test builds are also
/// fine because each test thread gets its own copy.
pub(crate) fn set_scope(class: &str) {
    BRICK_SCOPE.with(|s| *s.borrow_mut() = class.to_owned());
}

pub(crate) fn get_scope() -> String {
    BRICK_SCOPE.with(|s| s.borrow().clone())
}

thread_local! {
    static BRICK_SCOPE: std::cell::RefCell<String> = const { std::cell::RefCell::new(String::new()) };
}

/// Prefix each CSS selector in `css` with `.{scope}` and inject a `<style>`
/// element into the document. Called at render time by the `style!` macro.
/// No-op in test builds (no DOM available).
pub fn inject_scoped_style(css: &str, scope: &str) {
    let _ = (css, scope);
    #[cfg(brick_dom)]
    {
        use wasm_bindgen::JsCast;
        let scoped = scope_css(css, scope);
        let document = web_sys::window().unwrap().document().unwrap();
        let style_el = document.create_element("style").unwrap();
        style_el.set_inner_html(&scoped);
        document
            .body()
            .unwrap()
            .append_child(style_el.unchecked_ref())
            .unwrap();
    }
}

/// Wrap a DOM-mutating callback in `document.startViewTransition()` when available,
/// falling back to a direct call when the API is absent. No-op wrapper in test builds.
#[cfg(brick_dom)]
pub(crate) fn start_view_transition(callback: impl FnOnce() + 'static) {
    use wasm_bindgen::JsCast;
    use wasm_bindgen::closure::Closure;
    let doc = web_sys::window().unwrap().document().unwrap();
    let start_vt = js_sys::Reflect::get(&doc, &"startViewTransition".into())
        .ok()
        .and_then(|v| v.dyn_into::<js_sys::Function>().ok());
    if let Some(f) = start_vt {
        let cb = Closure::once(callback);
        let _ = f.call1(&doc, cb.as_ref().unchecked_ref());
        cb.forget();
    } else {
        callback();
    }
}

/// Inject a raw CSS string into the page without any selector scoping.
/// Used by `keyframes!` and `Keyframes::inject()`. No-op in test builds.
pub fn inject_global_style(css: &str) {
    let _ = css;
    #[cfg(brick_dom)]
    {
        use wasm_bindgen::JsCast;
        let document = web_sys::window().unwrap().document().unwrap();
        let style_el = document.create_element("style").unwrap();
        style_el.set_inner_html(css);
        document
            .body()
            .unwrap()
            .append_child(style_el.unchecked_ref())
            .unwrap();
    }
}

fn scope_css(css: &str, scope: &str) -> String {
    let mut result = String::new();
    for block in css.split('}') {
        let block = block.trim();
        if block.is_empty() {
            continue;
        }
        if let Some(brace) = block.find('{') {
            let selectors = block[..brace].trim();
            let declarations = block[brace + 1..].trim();
            let scoped: String = selectors
                .split(',')
                .map(|s| format!(".{} {}", scope, s.trim()))
                .collect::<Vec<_>>()
                .join(", ");
            result.push_str(&scoped);
            result.push_str(" { ");
            result.push_str(declarations);
            result.push_str(" }\n");
        }
    }
    result
}

// ── CSS-on-mount deferred callbacks ──────────────────────────────────────────

/// Called by the `style!` proc macro to register reactive CSS custom property
/// observers. Closures are drained by `make_composite!` into `ViewComposite::on_mount`.
pub fn push_css_on_mount(f: Box<dyn Fn()>) {
    CSS_ON_MOUNT.with(|v| v.borrow_mut().push(std::rc::Rc::from(f)));
}

pub(crate) fn drain_css_on_mount() -> Vec<std::rc::Rc<dyn Fn()>> {
    CSS_ON_MOUNT.with(|v| v.borrow_mut().drain(..).collect())
}

/// Set a CSS custom property on the component scope element. Called by closures
/// emitted by `style!` for `{expr:spec}unit` dynamic values.
#[cfg(brick_dom)]
pub fn set_css_var_on_scope(scope: &str, var_name: &str, value: &str) {
    use wasm_bindgen::JsCast;
    if let Some(window) = web_sys::window() {
        if let Some(document) = window.document() {
            let selector = format!(".{}", scope);
            if let Ok(Some(el)) = document.query_selector(&selector) {
                let html_el = el.unchecked_into::<web_sys::HtmlElement>();
                let _ = html_el.style().set_property(var_name, value);
            }
        }
    }
}

thread_local! {
    static CSS_ON_MOUNT: std::cell::RefCell<Vec<std::rc::Rc<dyn Fn()>>> =
        const { std::cell::RefCell::new(Vec::new()) };
}

// Each html Element (and potentially custom built-ins) should have
// own top-level constructor and chainable builder methods

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escape_html_replaces_special_chars() {
        assert_eq!(escape_html("<b>a & b</b>"), "&lt;b&gt;a &amp; b&lt;/b&gt;");
    }

    #[test]
    fn escape_html_passthrough_plain_text() {
        assert_eq!(escape_html("hello world"), "hello world");
    }

    #[test]
    fn scope_css_prefixes_selector() {
        let out = scope_css("p { color: red }", "my-scope");
        assert_eq!(out.trim(), ".my-scope p { color: red }");
    }

    #[test]
    fn scope_css_handles_multi_selector() {
        let out = scope_css("h1, h2 { margin: 0 }", "s");
        assert!(out.contains(".s h1") && out.contains(".s h2"));
    }

    #[test]
    fn scope_css_empty_input() {
        assert_eq!(scope_css("", "s"), "");
    }
}
